name: Update Last Updated Date

on:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update last updated date
        run: |
          DATE=$(date +"%m/%d/%Y")
          sed -i "s/Last updated: .*/Last updated: $DATE<\\/p>/" e:/tuckerstuff/Dev/bokkbokk.github.io/bokkbokk.github.io/index.html

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add e:/tuckerstuff/Dev/bokkbokk.github.io/bokkbokk.github.io/index.html
          git commit -m "Update last updated date to $DATE"
          git push